# This is a basic workflow to help you get started with Actions

name: Test Concurrency
run-name: Test concurrency with id = ${{ inputs.concurrencyId }} {{ inputs.isCancelInProgress ? "and could be interrupted"  }} 
# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      concurrencyId:
        description: "Concurrency Id"
        type: string
        required: true
      isCancelInProgress:
        description: "Is cancel in progress"
        type: boolean

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  testConcurrency:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    concurrency:
      group: group-${{ inputs.concurrencyId }}
      cancel-in-progress: ${{ inputs.isCancelInProgress }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: date
      
      - run: |
          echo "CONCURRENCY_ID: $CONCURRENCY_ID"
          echo "IS_CANCEL_IN_PROGRESS: $IS_CANCEL_IN_PROGRESS"
        env:
          CONCURRENCY_ID: ${{ inputs.concurrencyId }}
          IS_CANCEL_IN_PROGRESS: ${{ inputs.isCancelInProgress }}

      - uses: jakejarvis/wait-action@v0.1.1
        with:
            # Follows the Linux sleep syntax for time units: a number followed by s for seconds, m for minutes, etc
          time: "30s"
      - run: date
      - run: echo "Finished!"
